const words = {
  Tiere: [
    'Hund', 'Katze', 'Maus', 'Pferd', 'Kuh', 'Schaf', 'Ziege', 'Schwein',
    'Huhn', 'Hahn', 'Ente', 'Gans', 'Kaninchen', 'Hamster', 'Goldfisch',
    'Papagei', 'Wellensittich', 'Taube', 'Rabe', 'Spatz', 'Amsel', 'Storch',
    'Adler', 'Eule', 'Pfau', 'Pinguin', 'Seehund', 'Wal', 'Delfin', 'Hai',
    'Krabbe', 'Qualle', 'Krokodil', 'Nilpferd', 'Giraffe', 'Löwe', 'Tiger',
    'Bär', 'Wolf', 'Fuchs', 'Eichhörnchen', 'Igel', 'Wildschwein', 'Reh',
    'Hirsch', 'Affe', 'Gorilla', 'Känguru', 'Koala', 'Panda', 'Waschbär',
    'Otter', 'Dachs', 'Maulwurf', 'Fledermaus', 'Schmetterling', 'Biene',
    'Wespe', 'Hummel', 'Ameise', 'Marienkäfer', 'Käfer', 'Libelle',
    'Grashüpfer', 'Schnecke', 'Wurm', 'Spinne', 'Fisch', 'Karpfen',
    'Forelle', 'Barsch', 'Hecht', 'Lachs', 'Seepferdchen', 'Muschel',
    'Seestern', 'Kamel', 'Esel', 'Schlange', 'Frosch', 'Kröte',
    'Kakerlake', 'Mücke', 'Zecke', 'Floh', 'Krebs', 'Hummer', 'Garnele',
    'Robbe', 'Faultier', 'Zebra', 'Lama', 'Oktopus', 'Seelöwe', 'Yak',
    'Alpaka', 'Meerschweinchen', 'Marder', 'Delfin', 'Flamingo', 'Strauß',
    'Schwan', 'Emu', 'Pelikan', 'Nashorn', 'Leopard', 'Gepard', 'Bison',
    'Stachelschwein', 'Luchs', 'Wombat', 'Pavian',
    'Waschbär', 'Ameisenbär', 'Waran', 'Capybara',
    'Kakadu', 'Lemur'],
  Länder: [ "Deutschland",
  "Italien",
  "Spanien",
  "Frankreich",
  "Schweden",
  "Norwegen",
  "Australien",
  "Kanada",
  "Brasilien",
  "Schweiz",
  "Japan",
  "Türkei",
  "Indien",
  "Südafrika",
  "USA",
  "Ostfriesland",
  "Bayern",
  "Sibirien",
  "Vatikanstadt",
  "Kleinwalsertal",
  "Nordkorea",
  "Mittelmeerinsel",
  "Transsilvanien",
  "Himalaya",
  "Texas",
  "Hollywood",
  "Alaska",
  "Grönland",
  "Korsika",
  "Mallorca",
  "Ibiza",
  "Sylt",
  "Monaco",
  "Luxemburg",
  "Liechtenstein",
  "San Marino",
  "Kongo",
  "Hongkong",
  "New York",
  "Dubai",
  "Südpol",
  "Nordpol",
  "Andorra",
  "Malediven",
  "Malediven",
  "Mallorca",
  "Kenia",
  "Tokio",
  "Singapur",
  "Hawaii",
  "Bermuda",
  "Kreml", 
  "Atlantis",
  "Silicon Valley",
  "Antarktis",
  "Sahara",
  "Westerwald",
  "Eifel",
  "Moskau",
  "Toskana",
  "Schwarzwald",
  "Amazonas",
  "Karibik",
  "Route 66",
  "Balkan",
  "Bretagne",
  "Fußballnation",
  "Einkaufsparadies",
  "Weihnachtsland",
  "Märchenland",
  "Paradiesinsel" ],
  Berufe: [
  "Bestattungsunternehmer",
  "Leichenwäscher",
  "Matratzen-Tester",
  "Influencer",
  "OnlyFans-Star",
  "Dosenpfand-Sammler",
  "Dönerbudenbesitzer",
  "Shisha-Bar-Betreiber",
  "Wurstfachverkäufer",
  "Politiker",
  "Klofrau",
  "Mülltaucher",
  "Stripper",
  "Hochstapler",
  "Arbeitsloser",
  "TikToker",
  "Hausmeister",
  "Wasserrutschentester",
  "Pizzabote",
  "Imbissbudenwart",
  "Schornsteinfeger",
  "Hausfrau",
  "Möchtegern-Rapper",
  "Steuerhinterzieher",
  "YouTuber",
  "Bierbrauer",
  "Schnapsbrenner",
  "Puffbesitzer",
  "Alkoholtester",
  "FIFA-Präsident",
  "Reichsbürger",
  "Lotto-Millionär",
  "Fortnite-Streamer",
  "Schwarzfahrer",
  "Kioskbesitzer",
  "Kiffer",
  "Praktikant",
  "Weihnachtsmann",
  "Geldwäscher",
  "Schulschwänzer",
  "Motivationscoach",
  "Fake-Prinz"
  ],
  Random: ["Megaritter", "Mercy-Main", "König Thomas", "Saarland", "Bob Tschigerillo", "Radiant", "Inder", "GTI-Fahrer", "Abbelschorle", "Gooner", "Make-a-Wish", "Poposex", "Arbeitszeitbetrug", "Emochaya", "Andrew Tate", "Rainer Winkler", "Nougatbits", "Carbonat Erol", "Türkentasche", "ApoRed", "Schoko Crossaint", "Lidl",  , "Renegade Raider", "Bob Ross", "ChatGPT", "Taube", "Paulaner Spezi", "Spotify", "Tiktok", "Digda", "Die Olchis", "Elektrogiant", "Geoguessr", "BTD 6", "GTA 6", "2.6", "Discord", "Chicken Jockey", "McDonaldas", "Golem", "Monster AG", "Durstlöscher", "Sprudel Wasser", "Skibidi Toilet", "20 Chicken Nuggets", "Rothschild", "KFC Bucket", "Saturn", "Wehinachtsmann und Co.KG", "Epic Games", "Weißer Monster", "Redbull grün", "Himbeeren", "Jägermeister", "Airfryer", "Sonnenblumenkerne", "Nutella", "Airpods", "Stand Up Comedy", "Squid Game", "Friedhof", "Ariel 3 in 1 Pods", "Lays Chips", "Wii Sport"],
  Promis: ["Angela Merkel", "Donald Trump", "Elon Musk", "Jeff Bezos", "Kanye West", "Friedrich Merz", "Olaf Scholz", "Joe Biden", "Vladimir Putin", "Xi Jinping", "Dwayne Johnson (The Rock)", "Marc Andre Ter Stegen", "Julius Caesar", "Napoleon Bonaparte", "Bojack Horseman", "Albert Einstein", "Karin Ritter", "Gurkensohn", "Moneyboy", "Coldmirror", "Boss Baby", "Ralf Schumacher", "Helene Fischer", "ApoRed", "Y-Titty", "Simon Desue", "ConCrafter", "BastiGHG", "Mrs. Incredible", "Kim Possible", "MrWissen2go", "Willi wills wissen", "Rezo", "Gronkh", "Unge", "Paluten", "MontanaBlack", "Katja Krasavice", "BibisBeautyPalace", "Shirin David", "Thomas Gottschalk", "Steve", "Shaggy", "Franz Kafka", "Martin Luther", "Christian Wolf", "Justus Jonas", "Donald Duck", "Homer Simpson", "Maggy Simpson", "Rodrick Hefffley (Gregs großer Bruder)", "Peter Lustig", "Stewie", "Bernd das Brot", "Merkel", "Gzuz", "Kollegah", "Richterin Barbara Salesch", "Adin Ross", "Icarly", "Logan Paul", "Lester (GTA)", "Dream", "Young Sheldon", "Sensei Wu", "Po (Kongfu Panda)", "Master Shifu", "Steven Hawking", "Peter Griffin", "Alexander der Große", "Dobby", "Gini Wesley", "Padme Amidala", "C3PO", "Mort (Fuße)", "King Julien", "Egon Kowalski", "Skipper", "Wall-E", "Gru", "Baby Groot", "Thanos", "Ryan Reynolds", "Adam Sandler", "Lebron", "Walter White", "Morgan Freeman", "Ashoka", "Phineas", "Candice", "Dr. Dofenschmirz", "Robin Hood", "Lightning McQueen", "Daniel Jung", "Shrek", "Rick Sanchez", "Relaxo", "Jesus", "Messi", "CR7", "Kobe Bryant", "Lego Batman", "Manetti", "Sherwood", "Mr. Crabs", "Gelbes M&M", "Chewbacca", "John F. Kennedy", "Kelvin (Prankbros)", "Maggus Rühl", "Bob Tschigerillo", "Michael Scofield", "Dumbledore", "Kleiner Roter Tracktor", "Tom (Tom und das Erdbeermarmeladenbrot mit Honig)", "John Pork", "Magnus Carlsen", "Zenyatta", "Marcel Davis", "Tung Tung Tung Tung Sahur", "Reyna", "Guller BBQ", "Lewis Hamilton", "Otto Waalkes", "Elyas M'barek", "George Floyd", "Speed", "Militante Veganerin", ],
  Dinge: ["Sand", "Kariertes Papier", "Bierdeckel", "Sales", "Kreide", "Fußboden", "Verstärker", "Zahnbürste", "Wii Nunchucks", "Hochdruckreiniger", "7 Up", "Triangel", "Yoguhrt", "Plastikflaschen", "Sagrotan", "Blobfisch", "Bürostuhl (kein Lederstuhl)", "Autos mit USB Port", "Katzenzungen", "Türstopper", "Tuba", "Aspirin", "Tennis Ball", "Batmobil", "Hubba Bubba", "Batterien", "Rasierschaum", "Pummelparty", "Dackel", "Mond", "Hockey", "Knöpfe", "Badelatschen", "Shampoo", "Schottländer", "Leopard", "Socken", "Eis", "Pappe", "Trainspotter", "Stoppschild", "Tortillas", "Vor dem Wecker aufwachen", "Schlüssel", "Erdbeeren", "Metrisches System", "instant Nudeln"]
  

};

module.exports = words;